version: '3'
services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - <server_mount_path>:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]